Repository beyond-sw-camp/be06-2nd-Dopamines-BOOT_UP, pull requests merged in 2024-07, with the labels that each got.

#11 [#5] [User] 일반 회원 로그인 기능 구현 + JWT 적용
  src/main/java/com/example/dopamines/domain/user/controller/UserController.java
  src/main/java/com/example/dopamines/domain/user/controller/sample.java
  src/main/java/com/example/dopamines/domain/user/model/entity/User.java
  src/main/java/com/example/dopamines/domain/user/model/entity/sample.java
  src/main/java/com/example/dopamines/domain/user/model/request/UserLoginRequest.java
  src/main/java/com/example/dopamines/domain/user/model/request/UserSignupRequest.java
  src/main/java/com/example/dopamines/domain/user/model/request/sample.java
  src/main/java/com/example/dopamines/domain/user/model/response/UserSignupResponse.java
  src/main/java/com/example/dopamines/domain/user/model/response/sample.java
  src/main/java/com/example/dopamines/domain/user/repository/UserRepository.java
  src/main/java/com/example/dopamines/domain/user/repository/sample.java
  src/main/java/com/example/dopamines/domain/user/service/UserService.java
  src/main/java/com/example/dopamines/domain/user/service/sample.java
Labels: Backend, feat✨

#14 [#3] [Feat] 프로젝트 게시판 개발
  src/main/java/com/example/dopamines/domain/board/project/controller/ProjectBoardController.java
  src/main/java/com/example/dopamines/domain/board/project/controller/sample.java
  src/main/java/com/example/dopamines/domain/board/project/model/entity/ProjectBoard.java
  src/main/java/com/example/dopamines/domain/board/project/model/entity/sample.java
  src/main/java/com/example/dopamines/domain/board/project/model/request/ProjectBoardReq.java
  src/main/java/com/example/dopamines/domain/board/project/model/request/UpdateProjectBoardReq.java
  src/main/java/com/example/dopamines/domain/board/project/model/request/sample.java
  src/main/java/com/example/dopamines/domain/board/project/model/response/ProjectBoardRes.java
  src/main/java/com/example/dopamines/domain/board/project/model/response/ReadProjectBoardRes.java
  src/main/java/com/example/dopamines/domain/board/project/model/response/sample.java
  src/main/java/com/example/dopamines/domain/board/project/repository/ProjectBoardRepository.java
  src/main/java/com/example/dopamines/domain/board/project/repository/sample.java
  src/main/java/com/example/dopamines/domain/board/project/service/CloudFileUploadService.java
  src/main/java/com/example/dopamines/domain/board/project/service/ProjectBoardService.java
  src/main/java/com/example/dopamines/domain/board/project/service/sample.java
Labels: Backend, feat✨

#13 [#2] [Market] 중고마켓 게시판 기능 개발
  src/main/java/com/example/dopamines/domain/board/market/controller/MarkedController.java
  src/main/java/com/example/dopamines/domain/board/market/controller/MarketBoardController.java
  src/main/java/com/example/dopamines/domain/board/market/controller/sample.java
  src/main/java/com/example/dopamines/domain/board/market/mapper/MarketBoardMapper.java
  src/main/java/com/example/dopamines/domain/board/market/mapper/ProductImageMapper.java
  src/main/java/com/example/dopamines/domain/board/market/mapper/sample.java
  src/main/java/com/example/dopamines/domain/board/market/model/dto/MarketBoardDTO.java
  src/main/java/com/example/dopamines/domain/board/market/model/dto/sample.java
  src/main/java/com/example/dopamines/domain/board/market/model/entity/MarkedPost.java
  src/main/java/com/example/dopamines/domain/board/market/model/entity/MarketPost.java
  src/main/java/com/example/dopamines/domain/board/market/model/entity/ProductImage.java
  src/main/java/com/example/dopamines/domain/board/market/model/entity/sample.java
  src/main/java/com/example/dopamines/domain/board/market/repository/MarkedPostRepository.java
  src/main/java/com/example/dopamines/domain/board/market/repository/MarketPostRepository.java
  src/main/java/com/example/dopamines/domain/board/market/repository/ProductImageRepository.java
  src/main/java/com/example/dopamines/domain/board/market/repository/querydsl/MarketPostRepositoryCustom.java
  src/main/java/com/example/dopamines/domain/board/market/repository/querydsl/MarketPostRepositoryCustomImpl.java
  src/main/java/com/example/dopamines/domain/board/market/repository/querydsl/sample.java
  src/main/java/com/example/dopamines/domain/board/market/repository/sample.java
  src/main/java/com/example/dopamines/domain/board/market/service/MarkedService.java
  src/main/java/com/example/dopamines/domain/board/market/service/MarketService.java
  src/main/java/com/example/dopamines/domain/board/market/service/sample.java
  src/main/java/com/example/dopamines/global/infra/s3/CloudFileUploadService.java
  src/main/java/com/example/dopamines/global/security/CustomUserDetails.java
Labels: Backend, feat✨

#15 [Feat] 공지사항 게시판 기능 구현
  src/main/java/com/example/dopamines/domain/board/notice/controller/NoticeController.java
  src/main/java/com/example/dopamines/domain/board/notice/model/entity/Notice.java
  src/main/java/com/example/dopamines/domain/board/notice/model/request/NoticeRequestDto.java
  src/main/java/com/example/dopamines/domain/board/notice/model/response/NoticeResponseDto.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepository.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepositoryImpl.java
  src/main/java/com/example/dopamines/domain/board/notice/service/NoticeService.java
  src/main/java/com/example/dopamines/global/aop/AdministrationAspect.java
  src/main/java/com/example/dopamines/global/common/BaseResponseStatus.java
  src/main/java/com/example/dopamines/global/common/annotation/CheckAdmin.java
Labels: Backend, feat✨

#16 [Feat] 자유 게시판 기능 초기 구현
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeBoardController.java
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeCommentController.java
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeLikeController.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeBoard.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeComment.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeCommentLike.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeLike.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeRecomment.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeRecommentLike.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/sample.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/FreeBoardReq.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/FreeLikeReq.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/UpdateFreeBoardReq.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/sample.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeBoardReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeBoardRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeLikeRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreeBoardRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreeCommentRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreeLikeRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/sample.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeBoardService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeLikeService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/sample.java
Labels: Backend, feat✨

#17 [#8] [Feat] 관리자 회원 관리 기능 구현
  src/main/java/com/example/dopamines/domain/admin/controller/AdminController.java
  src/main/java/com/example/dopamines/domain/admin/model/request/AdminSignupRequest.java
  src/main/java/com/example/dopamines/domain/admin/model/request/UserAssignedRequest.java
  src/main/java/com/example/dopamines/domain/admin/model/request/UserBlackRequest.java
  src/main/java/com/example/dopamines/domain/admin/service/AdminService.java
  src/main/java/com/example/dopamines/domain/user/model/entity/User.java
  src/main/java/com/example/dopamines/global/security/CustomUserDetails.java
  src/main/java/com/example/dopamines/global/security/SecurityConfig.java
Labels: Backend, feat✨

#23 [#21] [Feat] 스터디 자리 예약 개발
  src/main/java/com/example/dopamines/InitDB.java
  src/main/java/com/example/dopamines/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/dopamines/domain/reservation/model/entity/Reservation.java
  src/main/java/com/example/dopamines/domain/reservation/model/entity/Seat.java
  src/main/java/com/example/dopamines/domain/reservation/model/request/ReservationReq.java
  src/main/java/com/example/dopamines/domain/reservation/model/request/SeatReq.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/ReservationListRes.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/ReservationRes.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/SeatRes.java
  src/main/java/com/example/dopamines/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/dopamines/domain/reservation/repository/SeatRepository.java
  src/main/java/com/example/dopamines/domain/reservation/service/ReservationService.java
Labels: Backend, feat✨

#27 [#21] [Feat] BaseResponseStatus 추가
  src/main/java/com/example/dopamines/global/common/BaseResponseStatus.java
Labels: Backend, feat✨

#20 [#1] [Feat] 회원가입 예외처리 추가
  src/main/java/com/example/dopamines/domain/user/controller/UserController.java
  src/main/java/com/example/dopamines/domain/user/model/request/UserSignupRequest.java
  src/main/java/com/example/dopamines/domain/user/service/UserEmailService.java
  src/main/java/com/example/dopamines/domain/user/service/UserService.java
  src/main/java/com/example/dopamines/global/common/BaseResponseStatus.java
Labels: Backend, feat✨

#30 [Feat] 자유 게시판 게시글 상세조회 기능 구현
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeBoardReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeCommentReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeBoardService.java
Labels: Backend, feat✨

#31 [#25] [Feat] 자유 게시판 기능 구현
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeBoardController.java
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeCommentController.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeBoard.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/FreeBoardReq.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/request/FreeBoardUpdateReq.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeBoardReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeBoardService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeCommentService.java
Labels: Backend, feat✨

#33 Feature/market chat
  src/main/java/com/example/dopamines/domain/chat/controller/ChatController.java
  src/main/java/com/example/dopamines/domain/chat/controller/ChatRoomController.java
  src/main/java/com/example/dopamines/domain/chat/mapper/ChatMessageMapper.java
  src/main/java/com/example/dopamines/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/example/dopamines/domain/chat/model/dto/ChatMessageDTO.java
  src/main/java/com/example/dopamines/domain/chat/model/dto/ChatRoomDTO.java
  src/main/java/com/example/dopamines/domain/chat/model/entity/ChatMessage.java
  src/main/java/com/example/dopamines/domain/chat/model/entity/ChatRoom.java
  src/main/java/com/example/dopamines/domain/chat/model/entity/ParticipatedChatRoom.java
  src/main/java/com/example/dopamines/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/dopamines/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/dopamines/domain/chat/repository/ParticipatedChatRoomRepository.java
  src/main/java/com/example/dopamines/domain/chat/service/ChatRoomService.java
  src/main/java/com/example/dopamines/domain/chat/service/MessageService.java
  src/main/java/com/example/dopamines/global/common/BaseResponseStatus.java
  src/main/java/com/example/dopamines/global/config/WebConfig.java
  src/main/java/com/example/dopamines/global/config/WebSocketConfig.java
  src/main/java/com/example/dopamines/global/interceptor/StompHandler.java
  src/main/java/com/example/dopamines/global/security/SecurityConfig.java
Labels: Backend, feat✨

#44 [#40][Feat] 공지사항 검색 기능 구현
  src/main/java/com/example/dopamines/domain/board/notice/controller/NoticeController.java
  src/main/java/com/example/dopamines/domain/board/notice/model/request/NoticeReq.java
  src/main/java/com/example/dopamines/domain/board/notice/model/response/NoticeRes.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepository.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/example/dopamines/domain/board/notice/repository/NoticeRepositoryImpl.java
  src/main/java/com/example/dopamines/domain/board/notice/service/NoticeService.java
Labels: Backend, feat✨

#45 [#7] [Feat] 자유 게시판 검색 기능 구현
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreePostController.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreePostRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreePostService.java
Labels: Backend, feat✨

#48 [#47] [Feat] 스터디 자리 조회 및 예약 가능 시간 조회 구현
  src/main/java/com/example/dopamines/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/dopamines/domain/reservation/model/request/ReservationReserveReq.java
  src/main/java/com/example/dopamines/domain/reservation/model/request/SeatReadDetailReq.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/ReservationReadByUserRes.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/ReservationReadRes.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/ReservationReserveRes.java
  src/main/java/com/example/dopamines/domain/reservation/model/response/SeatReadRes.java
  src/main/java/com/example/dopamines/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/dopamines/domain/reservation/repository/SeatRepository.java
  src/main/java/com/example/dopamines/domain/reservation/service/ReservationService.java
Labels: Backend, feat✨

#49 [#29] [Feat] 오픈 게시판 검색 기능 구현
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreePostRepository.java
  src/main/java/com/example/dopamines/domain/board/community/open/controller/OpenPostController.java
  src/main/java/com/example/dopamines/domain/board/community/open/repository/OpenPostRepository.java
  src/main/java/com/example/dopamines/domain/board/community/open/service/OpenPostService.java
Labels: Backend, feat✨

#57 [#56] [Fix] 프로젝트 게시판 수정
  src/main/java/com/example/dopamines/domain/board/project/controller/ProjectPostController.java
  src/main/java/com/example/dopamines/domain/board/project/repository/ProjectPostRepository.java
  src/main/java/com/example/dopamines/domain/board/project/service/ProjectPostService.java
Labels: Backend

#59 [#58] [ Fix] User정보 변경 Response 추가 및 Getter세팅
  src/main/java/com/example/dopamines/domain/admin/model/response/UserAssignedRes.java
  src/main/java/com/example/dopamines/domain/admin/model/response/UserBlackRes.java
  src/main/java/com/example/dopamines/domain/user/controller/UserController.java
Labels: Backend

#61 [#60] [Refactor]
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeCommentController.java
  src/main/java/com/example/dopamines/domain/board/community/free/controller/FreeRecommentController.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeComment.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreePost.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreePostImage.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/entity/FreeRecomment.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreeCommentReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/model/response/FreePostReadRes.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreeCommentRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreePostImageRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreePostRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/repository/FreeRecommentRepository.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeCommentService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeLikeService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreePostService.java
  src/main/java/com/example/dopamines/domain/board/community/free/service/FreeRecommentService.java
  src/main/java/com/example/dopamines/domain/user/model/entity/User.java
  src/main/java/com/example/dopamines/global/aop/MethodExcutionTimer.java
  src/main/java/com/example/dopamines/global/common/annotation/Timer.java
Labels: enhancement
